/**
 * Curated FinScroll cards in the Learn v2 schema.
 *
 * Each card declares everything five frames need (Hook → Visual → Insight
 * → Quiz → Action), plus learning-graph metadata (related cards,
 * prerequisites, mini-series membership), plus per-onboarding-segment
 * personalization templates for Frame 3.
 */
import type { Card } from "./types";

export const CARDS: readonly Card[] = [
  // ── BEGINNER ─────────────────────────────────────────────────────
  {
    id: 1,
    level: "Beginner",
    topic: "Budgeting",
    gradient: "from-emerald-800 via-emerald-950 to-zinc-950",
    emoji: "💰",
    title: "The 50/30/20 Rule",
    hook: "One rule. Total clarity over your money forever.",
    keyFact:
      "Split every paycheck: 50% needs, 30% wants, 20% savings and debt payoff. The SEC recommends this as the simplest starting framework for financial health.",
    insight: "Auto-split every paycheck before you spend a dollar.",
    impactLabel: "$3,000 salary → Savings",
    impactValue: "$600/mo",
    animation: "compounding-bars",
    visualData: [
      { label: "Needs (rent, food, bills)", value: "50%", percent: 50 },
      { label: "Wants (fun, subscriptions)", value: "30%", percent: 30 },
      { label: "Savings + debt payoff", value: "20%", percent: 20 },
    ],
    personalizedTemplates: {
      saving: "Right now you save inconsistently. On $3,000/mo this rule alone moves $600 into your future.",
      debt: "20% of your paycheck on debt = freedom faster. Pair this rule with the avalanche method.",
      investing: "That 20% slice is your investment fuel. Send it straight to your brokerage on payday.",
      default: "Apply it once and the math runs itself for the next 40 years.",
    },
    quiz: {
      question: "On a $4,000/month salary using 50/30/20, how much goes to savings?",
      options: ["$400", "$800", "$1,200", "$2,000"],
      correctIndex: 1,
      explanation: "20% of $4,000 = $800 to savings and debt payoff each month.",
    },
    source: {
      name: "SEC Investor.gov — Save and Invest",
      url: "https://www.investor.gov/introduction-investing/investing-basics/save-and-invest",
    },
    videoEmbedUrl: "https://www.youtube.com/embed/VgZ2p0P0BBY",
    creator: "@finscroll_basics",
    relatedCardIds: [2, 3],
    miniSeries: "debt-killer",
  },
  {
    id: 2,
    level: "Beginner",
    topic: "Emergency Fund",
    gradient: "from-teal-800 via-teal-950 to-zinc-950",
    emoji: "🛡️",
    title: "Your Financial Airbag",
    hook: "One unexpected bill shouldn't ruin your life.",
    keyFact:
      "Hold 3–6 months of expenses in a high-yield savings account. This single habit separates financially stable people from those one bad month away from spiraling debt.",
    insight: "3–6 months of expenses, in cash, untouched.",
    impactLabel: "Avg unexpected expense",
    impactValue: "$3,500",
    animation: "shield",
    visualData: [
      { label: "Without emergency fund", value: "Debt spiral", percent: 100 },
      { label: "With 3-month fund", value: "Zero debt added", percent: 0 },
    ],
    personalizedTemplates: {
      saving: "If you're struggling to save, this is the FIRST goal. Beats investing, every time.",
      debt: "Build a $500-1,000 mini-fund first so a flat tire doesn't push you deeper into debt.",
      default: "Half of US adults can't cover a $400 surprise. Be the other half.",
    },
    quiz: {
      question: "Where should your emergency fund live?",
      options: [
        "Stock market for growth",
        "Under your mattress",
        "High-yield savings account",
        "Crypto for fast access",
      ],
      correctIndex: 2,
      explanation: "HYSA gives 4–5% APY while keeping funds instantly accessible. Stocks are too volatile for emergency money.",
    },
    source: {
      name: "SEC Investor.gov — Emergency Fund",
      url: "https://www.investor.gov/introduction-investing/investing-basics/glossary/emergency-fund",
    },
    videoEmbedUrl: "https://www.youtube.com/embed/dX-478R7HsU",
    creator: "@finscroll_basics",
    relatedCardIds: [1, 4],
    miniSeries: "debt-killer",
  },
  {
    id: 3,
    level: "Beginner",
    topic: "Compound Interest",
    gradient: "from-emerald-700 via-zinc-900 to-zinc-950",
    emoji: "🧋",
    title: "The 8th Wonder of the World",
    hook: "Einstein supposedly called this the most powerful force in the universe.",
    keyFact:
      "Interest earned on your interest. $1,000 at 8% annual return becomes $10,063 in 30 years without adding a single dollar. Time is the only variable you can't buy back.",
    insight: "Interest earned on your own interest.",
    impactLabel: "$1,000 at age 20",
    impactValue: "$10,063 by 50",
    animation: "growth-line",
    visualData: [
      { label: "Cash under mattress (30yr)", value: "$1,000", percent: 10 },
      { label: "At 8% compounded", value: "$10,063", percent: 100 },
    ],
    personalizedTemplates: {
      saving: "Even $50/month into an index fund hits ~$75k after 30 years at 8%. Start today, not next year.",
      investing: "This is why starting before 25 is worth more than starting with a 6-figure salary at 40.",
      default: "Compound only rewards patience. The math beats every shortcut you'll see online.",
    },
    quiz: {
      question: "What makes compound interest more powerful than simple interest?",
      options: [
        "Higher interest rates",
        "You earn interest on your interest",
        "Government tax benefits",
        "Lower risk",
      ],
      correctIndex: 1,
      explanation: "Compound interest earns returns on both principal AND previously earned interest — creating exponential growth over time.",
    },
    source: {
      name: "SEC Investor.gov — Compound Interest Calculator",
      url: "https://www.investor.gov/financial-tools-calculators/calculators/compound-interest-calculator",
    },
    videoEmbedUrl: "https://www.youtube.com/embed/jTW777ENc3c",
    creator: "@finscroll_basics",
    relatedCardIds: [1, 5],
    miniSeries: "debt-killer",
  },
  {
    id: 4,
    level: "Beginner",
    topic: "Inflation",
    gradient: "from-rose-800 via-rose-950 to-zinc-950",
    emoji: "📉",
    title: "The Silent Wealth Destroyer",
    hook: "Doing nothing with your money is actually losing money.",
    keyFact:
      "At 3% annual inflation, $10,000 today has only $7,374 of purchasing power in 10 years. Holding cash in a zero-interest account guarantees a slow loss.",
    insight: "Idle cash loses purchasing power every year.",
    impactLabel: "$10k cash after 10 yrs",
    impactValue: "$7,374 real value",
    animation: "alert-triangle",
    visualData: [
      { label: "Nominal value (on paper)", value: "$10,000", percent: 100 },
      { label: "Real purchasing power", value: "$7,374", percent: 74 },
    ],
    personalizedTemplates: {
      saving: "Saving alone isn't enough. Cash in a checking account is melting slowly. HYSA or index fund minimum.",
      default: "Inflation is the most predictable enemy in finance. Beat it by default, not by skill.",
    },
    quiz: {
      question: "At 3% annual inflation, what happens to $100 in a 0% interest account after 10 years?",
      options: ["It stays worth $100", "It grows slightly", "It loses ~26% of real value", "It doubles"],
      correctIndex: 2,
      explanation: "3% annual inflation compounds to a ~26% loss in purchasing power over 10 years.",
    },
    source: {
      name: "SEC Investor.gov — Inflation",
      url: "https://www.investor.gov/introduction-investing/investing-basics/glossary/inflation",
    },
    videoEmbedUrl: "https://www.youtube.com/embed/beAvFHP4wDI",
    creator: "@finscroll_basics",
    relatedCardIds: [2, 3, 5],
    miniSeries: "debt-killer",
  },

  // ── INTERMEDIATE ─────────────────────────────────────────────────
  {
    id: 5,
    level: "Intermediate",
    topic: "Passive Investing",
    gradient: "from-sky-800 via-sky-950 to-zinc-950",
    emoji: "📊",
    title: "Index Funds Beat 92% of Experts",
    hook: "Most Wall Street pros can't beat a robot that doesn't try.",
    keyFact:
      "Over any 15-year period, 92% of actively managed funds underperform a simple S&P 500 index fund. Fees plus emotion compound into guaranteed underperformance.",
    insight: "Boring index funds outperform almost every active manager.",
    impactLabel: "$10k → 30 yrs @ 8%",
    impactValue: "$100,626",
    animation: "growth-line",
    visualData: [
      { label: "S&P 500 index fund", value: "$100,626", percent: 100 },
      { label: "Avg active fund (after fees)", value: "$57,435", percent: 57 },
    ],
    personalizedTemplates: {
      investing: "Your first investment should be a broad index fund. VOO, VTI, or your country equivalent.",
      default: "Picking individual stocks is a status game. Index funds are a wealth game.",
    },
    quiz: {
      question: "What % of actively managed funds fail to beat the S&P 500 over 15 years?",
      options: ["About 30%", "About 55%", "Over 92%", "Under 10%"],
      correctIndex: 2,
      explanation: "Per Elsevier research, 92%+ of actively managed funds underperform a passive index fund over 15 years.",
    },
    source: {
      name: "SEC Investor.gov — Index Fund",
      url: "https://www.investor.gov/introduction-investing/investing-basics/glossary/index-fund",
    },
    videoEmbedUrl: "https://www.youtube.com/embed/x7pcbfzYSQY",
    creator: "@finscroll_investing",
    relatedCardIds: [3, 6, 7],
    miniSeries: "first-investment",
  },
  {
    id: 6,
    level: "Intermediate",
    topic: "Tax-Advantaged Accounts",
    gradient: "from-cyan-800 via-sky-950 to-zinc-950",
    emoji: "🏦",
    title: "Roth IRA: Legal Tax Hack",
    hook: "An account that grows your money 100% tax-free, forever.",
    keyFact:
      "Roth IRA: contribute after-tax dollars now, pay ZERO tax on growth or withdrawals. $6,500/yr from age 22 to 65 at 8% returns ≈ $2.1M tax-free. This is legal.",
    insight: "$2.1M tax-free retirement is real if you start before 25.",
    impactLabel: "Roth IRA at retirement",
    impactValue: "$2.1M tax-free",
    animation: "compounding-bars",
    visualData: [
      { label: "Tax-free Roth growth", value: "$2.1M kept", percent: 100 },
      { label: "Taxable account (35% tax)", value: "$1.37M kept", percent: 65 },
    ],
    personalizedTemplates: {
      investing: "Roth is the first investment account most people should open. Cheaper than skipping it.",
      default: "Every year of skipped contribution = ~$50k of future retirement gone.",
    },
    quiz: {
      question: "When do you pay taxes on a Roth IRA?",
      options: [
        "When you withdraw at retirement",
        "Annually on capital gains",
        "Only on contributions; growth is tax-free",
        "Every year on earnings",
      ],
      correctIndex: 2,
      explanation: "Pay tax upfront on contributions (after-tax dollars). All growth and qualified withdrawals are tax-free forever.",
    },
    source: {
      name: "SEC Investor.gov — Roth IRA",
      url: "https://www.investor.gov/introduction-investing/investing-basics/glossary/roth-ira",
    },
    videoEmbedUrl: "https://www.youtube.com/embed/aILcPeU2YjQ",
    creator: "@finscroll_investing",
    relatedCardIds: [5, 9],
    miniSeries: "first-investment",
  },
  {
    id: 7,
    level: "Intermediate",
    topic: "Behavioral Finance",
    gradient: "from-indigo-800 via-sky-950 to-zinc-950",
    emoji: "🤖",
    title: "DCA Beats Emotion",
    hook: "The most profitable thing you can do is make investing boring.",
    keyFact:
      "Dollar-cost averaging: invest a fixed amount on a fixed schedule regardless of market conditions. When prices drop you buy more shares. When they rise you buy fewer. You win either way.",
    insight: "Automate it. Forget about it. Watch it grow.",
    impactLabel: "DCA vs lump sum (bear mkt)",
    impactValue: "+23% better",
    animation: "growth-line",
    visualData: [
      { label: "DCA on autopilot", value: "Lower avg cost", percent: 85 },
      { label: "Timing the market", value: "95% fail", percent: 5 },
    ],
    personalizedTemplates: {
      investing: "Set up an auto-transfer the day after each payday. You'll never miss money you didn't see.",
      default: "Boring investors retire rich. Exciting ones retire late.",
    },
    quiz: {
      question: "What is the key advantage of DCA?",
      options: [
        "You always buy at the lowest price",
        "It removes emotion from investing",
        "It guarantees higher returns than lump sum",
        "It only works in bull markets",
      ],
      correctIndex: 1,
      explanation: "DCA removes timing decisions — you invest consistently regardless of conditions, averaging your cost basis.",
    },
    source: {
      name: "SEC Investor.gov — Dollar Cost Averaging",
      url: "https://www.investor.gov/introduction-investing/investing-basics/glossary/dollar-cost-averaging",
    },
    videoEmbedUrl: "https://www.youtube.com/embed/ZFEnwg54Zj4",
    creator: "@finscroll_investing",
    relatedCardIds: [5, 8],
    miniSeries: "first-investment",
  },

  // ── ADVANCED ─────────────────────────────────────────────────────
  {
    id: 8,
    level: "Advanced",
    topic: "Portfolio Theory",
    gradient: "from-violet-800 via-violet-950 to-zinc-950",
    emoji: "⚖️",
    title: "Diversification: The Free Lunch",
    hook: "Markowitz won a Nobel Prize for proving you can lower risk without lowering return.",
    keyFact:
      "By combining assets with low correlation (stocks + bonds + real estate), you reduce portfolio volatility WITHOUT sacrificing expected return. Risk-adjusted performance improves mechanically.",
    insight: "Lower risk without lower return — yes, really.",
    impactLabel: "Portfolio volatility cut",
    impactValue: "−40% risk",
    animation: "compounding-bars",
    visualData: [
      { label: "100% stocks (high vol)", value: "σ = 18%/yr", percent: 100 },
      { label: "60/40 diversified", value: "σ = 11%/yr", percent: 61 },
    ],
    personalizedTemplates: {
      default: "Even one bond index fund alongside stocks measurably reduces your drawdowns.",
    },
    quiz: {
      question: "Why does diversification reduce risk without reducing expected returns?",
      options: [
        "You hold safer assets with lower returns",
        "Uncorrelated assets cancel each other's volatility",
        "Government guarantees protect diversified portfolios",
        "You pay less in taxes",
      ],
      correctIndex: 1,
      explanation: "When assets don't move together (low correlation), losses in one are offset by gains in another. The math shows variance falls without expected return falling.",
    },
    source: {
      name: "SEC Investor.gov — Diversification",
      url: "https://www.investor.gov/introduction-investing/investing-basics/glossary/diversification",
    },
    videoEmbedUrl: "https://www.youtube.com/embed/XQ1h-meP_rw",
    creator: "@finscroll_advanced",
    relatedCardIds: [7, 9, 10],
  },
  {
    id: 9,
    level: "Advanced",
    topic: "Factor Investing",
    gradient: "from-purple-800 via-violet-950 to-zinc-950",
    emoji: "🔬",
    title: "The 5 Factors of Return",
    hook: "Fama and French proved the market has predictable patterns.",
    keyFact:
      "Fama-French 5-Factor Model: Market, Size (small beats large), Value (cheap beats expensive), Profitability, Investment. Decades of academic data confirm a persistent value+size premium.",
    insight: "Tilt towards small-value to earn a measurable premium.",
    impactLabel: "Small-cap value premium",
    impactValue: "+3.5%/yr historical",
    animation: "spark",
    visualData: [
      { label: "Market return (beta only)", value: "8% avg", percent: 70 },
      { label: "Small-cap value tilt", value: "11.5% avg", percent: 100 },
    ],
    personalizedTemplates: {
      default: "Once your core is set, a small tilt towards small-cap value can compound meaningfully.",
    },
    quiz: {
      question: "In Fama-French, which type of stocks historically outperform?",
      options: ["Large-cap growth", "High-momentum tech", "Small-cap value", "Government bonds"],
      correctIndex: 2,
      explanation: "Decades of academic research show small-cap value earns a persistent premium over large-cap growth.",
    },
    source: {
      name: "Kenneth R. French — Data Library",
      url: "https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/data_library.html",
    },
    videoEmbedUrl: "https://www.youtube.com/embed/J0nzBtY19OE",
    creator: "@finscroll_advanced",
    relatedCardIds: [5, 8],
    miniSeries: "tax-stack",
  },

  // ── QUANT ────────────────────────────────────────────────────────
  {
    id: 10,
    level: "Quant",
    topic: "Risk Metrics",
    gradient: "from-amber-800 via-amber-950 to-zinc-950",
    emoji: "⚡",
    title: "The Sharpe Ratio",
    hook: "Not all 20% returns are equal. Volatility matters as much as gain.",
    keyFact:
      "Sharpe = (Portfolio Return − Risk-Free Rate) / Standard Deviation. Measures return per unit of risk. Sharpe > 1.0 is good. > 2.0 is exceptional. Hedge funds aim for 1.5+.",
    insight: "Return per unit of risk is the only return that matters.",
    impactLabel: "Sharpe target (institutional)",
    impactValue: "≥ 1.5",
    animation: "spark",
    visualData: [
      { label: "High return, high vol (S=0.6)", value: "Mediocre", percent: 40 },
      { label: "Steady return, low vol (S=1.8)", value: "Excellent", percent: 100 },
    ],
    personalizedTemplates: {
      default: "When someone brags about a 30% year, ask their Sharpe ratio. Probably awful.",
    },
    quiz: {
      question: "Fund A: 20% return, 25% vol. Fund B: 12% return, 8% vol. Risk-free: 4%. Which has better Sharpe?",
      options: ["A — higher absolute return", "B — Sharpe ≈ 1.0 vs A ≈ 0.64", "They are equal", "Cannot determine"],
      correctIndex: 1,
      explanation: "A: (20-4)/25 = 0.64. B: (12-4)/8 = 1.0. B provides more return per unit of risk.",
    },
    source: {
      name: "SEC Investor.gov — Sharpe Ratio",
      url: "https://www.investor.gov/introduction-investing/investing-basics/glossary/sharpe-ratio",
    },
    videoEmbedUrl: "https://www.youtube.com/embed/vTzjk6kLw2I",
    creator: "@finscroll_quant",
    relatedCardIds: [8, 9, 11],
    miniSeries: "quant-foundations",
  },
  {
    id: 11,
    level: "Quant",
    topic: "Derivatives",
    gradient: "from-yellow-800 via-amber-950 to-zinc-950",
    emoji: "📐",
    title: "Options 101",
    hook: "90% of retail options traders lose money. Here's the math they don't show.",
    keyFact:
      "A call option gives you the RIGHT (not obligation) to buy 100 shares at a strike price before expiry. Max loss = premium paid. Max gain = unlimited. 90% of retail options buyers lose money.",
    insight: "Limited downside, unlimited upside — but stacked against you.",
    impactLabel: "Retail options loss rate",
    impactValue: "90% lose money",
    animation: "alert-triangle",
    visualData: [
      { label: "Options expire worthless", value: "~70%", percent: 70 },
      { label: "Profitable retail options traders", value: "< 10%", percent: 10 },
    ],
    personalizedTemplates: {
      default: "Understand options. Then probably don't trade them. The expected value is negative.",
    },
    quiz: {
      question: "Buy 1 call (100 shares) at $2 premium, strike $50, stock at $48. Maximum loss?",
      options: ["$4,800 (full stock value)", "$200 (premium paid)", "$50 per share × 100", "Unlimited"],
      correctIndex: 1,
      explanation: "Buying options caps your loss at premium paid. $2 × 100 = $200 max loss.",
    },
    source: {
      name: "SEC Investor.gov — Options",
      url: "https://www.investor.gov/introduction-investing/investing-basics/glossary/options",
    },
    videoEmbedUrl: "https://www.youtube.com/embed/jE8QsLKvOI4",
    creator: "@finscroll_quant",
    relatedCardIds: [10, 12],
    miniSeries: "quant-foundations",
  },
  {
    id: 12,
    level: "Quant",
    topic: "Asset Pricing",
    gradient: "from-orange-800 via-amber-950 to-zinc-950",
    emoji: "🧮",
    title: "CAPM in 60 Seconds",
    hook: "Every asset's expected return can be predicted with one equation.",
    keyFact:
      "Capital Asset Pricing Model: Expected Return = Risk-Free Rate + β × (Market Return − Risk-Free Rate). β = how much the asset moves with the market. β > 1 means more volatile than market, β < 1 means less.",
    insight: "β tells you how risky an asset is, relative to the market.",
    impactLabel: "If Rf=4%, Rm=10%, β=1.5",
    impactValue: "Expected return: 13%",
    animation: "spark",
    visualData: [
      { label: "Defensive (β = 0.5)", value: "7% expected", percent: 50 },
      { label: "Aggressive (β = 1.8)", value: "14.8% expected", percent: 100 },
    ],
    personalizedTemplates: {
      default: "If a stock has β = 2.0, it should return 2x the market premium. If it doesn't, skip it.",
    },
    quiz: {
      question: "An asset with β = 1.0 should…",
      options: [
        "Outperform the market",
        "Move exactly with the market",
        "Have zero risk",
        "Outperform during recessions",
      ],
      correctIndex: 1,
      explanation: "β = 1.0 means the asset moves 1-for-1 with the market. The S&P 500 itself has β = 1.0 by definition.",
    },
    source: {
      name: "SEC Investor.gov — Capital Asset Pricing Model",
      url: "https://www.investor.gov/introduction-investing/investing-basics/glossary/capital-asset-pricing-model",
    },
    videoEmbedUrl: "https://www.youtube.com/embed/5eBMyHBujw8",
    creator: "@finscroll_quant",
    relatedCardIds: [10, 11],
    miniSeries: "quant-foundations",
  },
];
